name: CI
on: [push, pull_request]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install pytest

      - name: Test
        run: |
          pytest

  release:
    # TODO: ADD ALL JOBS THAT MUST SUCCEED BEFORE RELEASING!
    needs: [test]
    # TODO: switch to master if that's the default branch
    if: github.ref_name == 'main' startsWith(github.ref, 'refs/tags') && github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install pkgmt twine wheel --upgrade

      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          TAG=$(git describe --abbrev=0)
          echo "tag is $TAG"
          pkgmt release $TAG --production --yes