name: Publish to PyPI
on: push


jobs:
  upload-to-pypi:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upload
        run: |
          python -m pip install --upgrade pip pkgmt
          TAG=$(git describe --abbrev=0)
          echo "tag is $TAG"
          pkgmt release $TAG --production